version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: cnt_users
        tests:
          - not_null
          - numeric

  - name: stg_user_events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: event_timestamp
        tests:
          - not_null

  - name: mart_unified
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: detector_id
        tests:
          - not_null
