version: 2

# Define a source
sources:
  - name: soccer
    schema: raw
    tables:
      - name: provider1_raw
      - name: provider2_raw
      - name: provider3_raw
      - name: club_elo
      - name: match_info
      - name: lineups
      - name: events
      - name: qualifiers
      - name: match_summary
      - name: player_position

# Define models
models:
  - name: stg_provider1
    description: "Staging model for provider1 data"
    columns:
      - name: provider_id
        tests:
          - unique
          - not_null
      - name: player_name
        tests:
          - not_null
      - name: gender
        tests:
          - not_null
          - accepted_values:
              values: ['Male', 'Female','M','F']

  - name: stg_provider2
    description: "Staging model for provider2 data"
    columns:
      - name: provider_id
        tests:
          - unique
          - not_null
      - name: player_name
        tests:
          - not_null
      - name: gender
        tests:
          - not_null
          - accepted_values:
              values: ['Male', 'Female','M','F']

  - name: stg_provider3
    description: "Staging model for provider3 data"
    columns:
      - name: provider_id
        tests:
          - unique
          - not_null
      - name: player_name
        tests:
          - not_null
      - name: gender
        tests:
          - not_null
          - accepted_values:
              values: ['Male', 'Female','M','F']

  - name: fct_player_id
    description: "global player_id table which helps in unique dentification"
      