version: 2

# Define a source
sources:
  - name: soccer
    schema: raw
    tables:
      - name: provider1_raw
      - name: provider2_raw
      - name: provider3_raw
      - name: club_elo
      - name: match_info
      - name: lineups
      - name: events
      - name: qualifiers
      - name: match_summary

# Define models
models:
  - name: stg_provider1
    description: "Staging model for provider1 data"
    # columns:
    #   - name: id
    #     description: "Primary key"
    #     tests:
    #       - unique
    #       - not_null

  - name: fct_player_id
    description: "Test"
      